// actionTypes.ts
export enum ActionType {
  FETCH_CUSTOMERS_REQUEST = "FETCH_CUSTOMERS_REQUEST",
  FETCH_CUSTOMERS_SUCCESS = "FETCH_CUSTOMERS_SUCCESS",
  FETCH_CUSTOMERS_FAILURE = "FETCH_CUSTOMERS_FAILURE",

  FETCH_CUSTOMER_DETAILS_REQUEST = "FETCH_CUSTOMER_DETAILS_REQUEST",
  FETCH_CUSTOMER_DETAILS_SUCCESS = "FETCH_CUSTOMER_DETAILS_SUCCESS",
  FETCH_CUSTOMER_DETAILS_FAILURE = "FETCH_CUSTOMER_DETAILS_FAILURE",

  FETCH_PHOTOS_REQUEST = "FETCH_PHOTOS_REQUEST",
  FETCH_PHOTOS_SUCCESS = "FETCH_PHOTOS_SUCCESS",
  FETCH_PHOTOS_FAILURE = "FETCH_PHOTOS_FAILURE",
  CHANGE_CUSTOMER = "CHANGE_CUSTOMER",
}
